# 本地构建CPU版本
build:
	docker build -f Dockerfile -t registry.cn-hangzhou.aliyuncs.com/aiminders/rl:latest .

# 本地构建GPU版本
build_gpu:
	docker build -f gpu.Dockerfile -t registry.cn-hangzhou.aliyuncs.com/aiminders/rl:latest-gpu .
